/**
 * Canonical ordering vectors generated by borsh-rs.
 *
 * borsh-rs sorts `HashMap` keys and `HashSet` elements by the key's `Ord`, and
 * `BTreeMap`/`BTreeSet` iterate in that order already. Each vector below is the
 * exact output of `rust/borsh_test/src/ordering_test.rs` for the same value,
 * listed here in the same (deliberately non-canonical) insertion order.
 */

import * as fs from "node:fs/promises"
import * as path from "node:path"
import { describe, expect, test } from "vitest"
import { b, type Schema } from "../../src/schema"

const utf8 = (text: string) => new TextEncoder().encode(text)
const testDataDir = path.join(__dirname, "..", "..", "rust", "borsh_test", "test_data")

// Rust: enum Color { Red, Green, Blue }
enum Color {
  Red = 0,
  Green = 1,
  Blue = 2,
}

// Rust: enum TagKey { Number(u8), Empty, Label(String) }
const TagKeySchema = b.enum({ Number: b.u8(), Empty: b.unit(), Label: b.string() })

interface Vector<T> {
  name: string
  schema: Schema<T>
  value: T
}

function vector<T>(name: string, schema: Schema<T>, value: T): Vector<unknown> {
  return { name, schema: schema as Schema<unknown>, value }
}

const vectors: Vector<unknown>[] = [
  vector(
    "bytes_map",
    b.hashMap(b.bytes(), b.bytes()),
    new Map([
      [utf8("zeta"), utf8("1")],
      [utf8("alpha"), utf8("2")],
      [utf8("alphabet"), utf8("3")],
      [new Uint8Array(), utf8("4")],
      [new Uint8Array([2]), utf8("5")],
      [new Uint8Array([10]), utf8("6")],
      [new Uint8Array([0x80]), utf8("7")],
      [new Uint8Array([9]), utf8("8")],
    ]),
  ),
  vector(
    "u32_map",
    b.hashMap(b.u32(), b.string()),
    new Map([
      [10, "ten"],
      [2, "two"],
      [1, "one"],
      [4294967295, "max"],
      [0, "zero"],
    ]),
  ),
  vector(
    "i32_map",
    b.hashMap(b.i32(), b.u8()),
    new Map([
      [-1, 1],
      [2, 2],
      [-10, 3],
      [-2147483648, 4],
      [2147483647, 5],
      [0, 6],
    ]),
  ),
  vector(
    "u64_map",
    b.hashMap(b.u64(), b.u8()),
    new Map([
      [10n, 1],
      [9n, 2],
      [100n, 3],
      [18446744073709551615n, 4],
    ]),
  ),
  vector(
    "i64_set",
    b.hashSet(b.i64()),
    new Set([-1n, 1n, -9223372036854775808n, 9223372036854775807n, 0n, -10n, 10n]),
  ),
  vector(
    "u128_set",
    b.hashSet(b.u128()),
    new Set([340282366920938463463374607431768211455n, 1n, 0n, 1n << 64n]),
  ),
  vector(
    "i128_set",
    b.hashSet(b.i128()),
    new Set([
      -170141183460469231731687303715884105728n,
      -1n,
      0n,
      170141183460469231731687303715884105727n,
    ]),
  ),
  vector(
    "string_map",
    b.hashMap(b.string(), b.u8()),
    new Map([
      ["\u{10000}", 1],
      ["￿", 2],
      ["a", 3],
      ["", 4],
      ["", 5],
      ["b", 6],
      ["ab", 7],
      ["퟿", 8],
      ["\u{1F600}", 9],
      ["\u{10FFFF}", 10],
    ]),
  ),
  vector("bool_set", b.hashSet(b.bool()), new Set([true, false])),
  vector(
    "option_map",
    b.hashMap(b.option(b.u8()), b.u8()),
    new Map([
      [5, 1],
      [null, 2],
      [0, 3],
      [255, 4],
    ]),
  ),
  vector(
    "tuple_set",
    b.hashSet(b.tuple(b.u8(), b.string())),
    new Set<[number, string]>([
      [1, "b"],
      [1, "a"],
      [0, "z"],
      [0, ""],
    ]),
  ),
  vector(
    "struct_map",
    b.hashMap(b.struct({ major: b.u8(), minor: b.u8() }), b.u8()),
    new Map([
      [{ major: 1, minor: 0 }, 1],
      [{ major: 0, minor: 255 }, 2],
      [{ major: 0, minor: 1 }, 3],
    ]),
  ),
  vector(
    "enum_map",
    b.hashMap(TagKeySchema, b.u8()),
    new Map<b.infer<typeof TagKeySchema>, number>([
      [{ Label: "x" }, 1],
      [{ Empty: {} }, 2],
      [{ Number: 5 }, 3],
      [{ Number: 1 }, 4],
      [{ Label: "" }, 5],
    ]),
  ),
  vector("vec_set", b.hashSet(b.vec(b.u16())), new Set([[2], [1, 2, 3], [1, 2], [], [1]])),
  vector(
    "array_set",
    b.hashSet(b.array(b.u8(), 2)),
    new Set([
      [1, 0],
      [0, 9],
      [0, 10],
    ]),
  ),
  vector(
    "native_enum_set",
    b.hashSet(b.nativeEnum(Color)),
    new Set([Color.Blue, Color.Red, Color.Green]),
  ),
  vector(
    "nested_set",
    b.hashSet(b.hashSet(b.u8())),
    new Set([new Set([2]), new Set([1, 3]), new Set<number>(), new Set([1])]),
  ),
  vector(
    "nested_map",
    b.hashMap(b.hashMap(b.u8(), b.u8()), b.u8()),
    new Map([
      [new Map<number, number>(), 1],
      [new Map([[1, 1]]), 2],
      [new Map([[1, 2]]), 3],
      [new Map([[0, 9]]), 4],
    ]),
  ),
]

describe("Borsh-RS Compatibility (canonical hashMap/hashSet ordering)", () => {
  test.each(vectors)(
    "$name matches borsh-rs bytes and round-trips",
    async ({ name, schema, value }) => {
      const rustBytes = new Uint8Array(
        await fs.readFile(path.join(testDataDir, `ordering_${name}.bin`)),
      )

      expect(schema.serialize(value)).toEqual(rustBytes)
      expect(schema.deserialize(rustBytes)).toEqual(value)
    },
  )
})
