[package]
name = "borsh_test"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.5", features = ["borsh-derive", "derive"] }
serde = { version = "1.0.217", features = ["derive"] }
